# Generated by Django 5.1.3 on 2025-01-14 09:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('output_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NiktoScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NmapScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('NIST', 'NIST'), ('COBIT', 'COBIT'), ('DPPA', 'DPPA'), ('CMA', 'CMA'), ('ISO27001', 'ISO27001'), ('SOC2', 'SOC2')], max_length=50)),
                ('compliance_status', models.CharField(default='Non-Compliant', max_length=50)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_scanner.ipaddress')),
            ],
        ),
    ]
