# Generated by Django 5.1.3 on 2025-01-16 21:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('output_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Prediction',
                'verbose_name_plural': 'AI Predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('framework', models.CharField(choices=[('NIST', 'NIST'), ('COBIT', 'COBIT'), ('DPPA', 'DPPA'), ('CMA', 'CMA'), ('ISO27001', 'ISO27001'), ('SOC2', 'SOC2')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance Rule',
                'verbose_name_plural': 'Compliance Rules',
                'ordering': ['framework', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'IP Addresses',
            },
        ),
        migrations.CreateModel(
            name='NiktoScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nikto Scan',
                'verbose_name_plural': 'Nikto Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NmapScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nmap Scan',
                'verbose_name_plural': 'Nmap Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('NIST', 'NIST'), ('COBIT', 'COBIT'), ('DPPA', 'DPPA'), ('CMA', 'CMA'), ('ISO27001', 'ISO27001'), ('SOC2', 'SOC2')], max_length=50)),
                ('compliance_status', models.CharField(default='Non-Compliant', max_length=50)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_audit_system.ipaddress')),
            ],
            options={
                'verbose_name': 'Compliance Status',
                'verbose_name_plural': 'Compliance Statuses',
                'ordering': ['ip_address', 'framework'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability', models.TextField()),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_audit_system.ipaddress')),
            ],
            options={
                'verbose_name': 'Scan Result',
                'verbose_name_plural': 'Scan Results',
                'ordering': ['-timestamp'],
            },
        ),
    ]
