# Generated by Django 5.1.3 on 2025-01-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_scanner', '0002_aipredictions_niktoscan_nmapscan_compliancestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aipredictions',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Prediction', 'verbose_name_plural': 'AI Predictions'},
        ),
        migrations.AlterModelOptions(
            name='compliancerule',
            options={'ordering': ['framework', 'rule_name'], 'verbose_name': 'Compliance Rule', 'verbose_name_plural': 'Compliance Rules'},
        ),
        migrations.AlterModelOptions(
            name='compliancestatus',
            options={'ordering': ['ip_address', 'framework'], 'verbose_name': 'Compliance Status', 'verbose_name_plural': 'Compliance Statuses'},
        ),
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name_plural': 'IP Addresses'},
        ),
        migrations.AlterModelOptions(
            name='niktoscan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nikto Scan', 'verbose_name_plural': 'Nikto Scans'},
        ),
        migrations.AlterModelOptions(
            name='nmapscan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nmap Scan', 'verbose_name_plural': 'Nmap Scans'},
        ),
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Scan Result', 'verbose_name_plural': 'Scan Results'},
        ),
    ]
