# Generated by Django 5.2.4 on 2025-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_scanner', '0003_alter_aipredictions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancerule',
            name='framework',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compliancestatus',
            name='framework',
            field=models.CharField(max_length=100),
        ),
    ]
